/**
 * Routes — "billing" domain.
 * AUTO-GENERATED by generate-complex-routes.ts
 */
import { z } from "zod";
import { defineRoutes } from "../../../src/base";
import { authMiddleware } from "../../../src/middleware";

// --- Schemas & shared types ---

const PricingModelSchema = z.discriminatedUnion("model", [
  z.object({ model: z.literal("flat"),     pricePerMonth: z.number().nonnegative(), pricePerYear: z.number().nonnegative() }),
  z.object({ model: z.literal("per_seat"), pricePerSeatMonth: z.number().nonnegative(), minSeats: z.number().int().min(1), maxSeats: z.number().int().nullable() }),
  z.object({ model: z.literal("usage"),    includedUnits: z.number().int().nonnegative(), pricePerOverageUnit: z.number().nonnegative(), unitLabel: z.string() }),
  z.object({ model: z.literal("hybrid"),   base: z.number().nonnegative(), perSeat: z.number().nonnegative(), includedSeats: z.number().int().nonnegative() }),
]);
type PricingModel = z.infer<typeof PricingModelSchema>;

const SubscriptionSchema = z.object({
  id: z.string(), orgId: z.string(),
  tier: z.enum(["free","starter","pro","business","enterprise"]),
  pricing: PricingModelSchema,
  status: z.enum(["active","trialing","past_due","cancelled","paused","incomplete"]),
  seats: z.number().int().min(1),
  currentPeriodStart: z.string().datetime(), currentPeriodEnd: z.string().datetime(),
  cancelAtPeriodEnd: z.boolean(),
  metadata: z.record(z.string(), z.string()),
  addons: z.array(z.object({ id:z.string(), name:z.string(), quantity:z.number().int().min(1), unitPrice:z.number().nonnegative() })).default([]),
});
type Subscription = z.infer<typeof SubscriptionSchema>;

// --- Route definitions ---

export const billingRoutes = defineRoutes({ middleware: [authMiddleware] })({
  /** Full subscription with pricing. */
  getSubscription(ctx) {
    return ctx.query(z.object({ orgId: z.string() }), (data) => ({ id:"sub_01", orgId:data.orgId, tier:"pro" as const, pricing:{ model:"per_seat", pricePerSeatMonth:12, minSeats:1, maxSeats:null } satisfies PricingModel, status:"active" as const, seats:10, currentPeriodStart: new Date().toISOString(), currentPeriodEnd: new Date().toISOString(), cancelAtPeriodEnd:false, metadata:{}, addons:[] } satisfies Subscription));
  },

  /** Proration preview. */
  previewUpgrade(ctx) {
    return ctx.query(z.object({ orgId: z.string(), targetTier: z.enum(["starter","pro","business","enterprise"]), targetSeats: z.number().int().min(1), billingInterval: z.enum(["monthly","annual"]) }), (data) => ({ currentAmount:12000, newAmount:24000, prorationAmount:6000, effectiveDate: new Date().toISOString(), lineItems: [] as Array<{ description:string; amount:number; currency:string }> }));
  },

  /** Stripe checkout session. */
  createCheckout(ctx) {
    return ctx.mutate(z.object({ orgId: z.string(), tier: z.enum(["starter","pro","business","enterprise"]), seats: z.number().int().min(1), billingInterval: z.enum(["monthly","annual"]), addons: z.array(z.object({ id:z.string(), quantity:z.number().int().min(1) })).default([]), successUrl: z.string().url(), cancelUrl: z.string().url(), couponCode: z.string().optional() }), (data) => ({ checkoutUrl:"https://checkout.stripe.com/pay/cs_xxx", sessionId:"cs_xxx" }));
  },

  /** Schedule cancellation. */
  cancelSubscription(ctx) {
    return ctx.mutate(z.object({ orgId: z.string(), reason: z.string().max(500).optional() }), (data) => ({ cancelAtPeriodEnd: true }));
  },

  /** Paginated invoice list. */
  invoices(ctx) {
    return ctx.query(z.object({ orgId: z.string(), limit: z.number().int().max(50).default(12), cursor: z.string().optional() }), (data) => ({ invoices: [] as Array<{ id:string; amount:number; currency:string; status:string; date:string }>, nextCursor: null as string | null }));
  },

  /** Invoice with line items. */
  getInvoice(ctx) {
    return ctx.query(z.object({ invoiceId: z.string() }), (data) => ({ id: data.invoiceId, lines: [] as Array<{ description:string; amount:number }>, total:0, currency:"usd" }));
  },

  /** Metered usage breakdown. */
  usageReport(ctx) {
    return ctx.query(z.object({ orgId: z.string(), breakdown: z.enum(["daily","weekly","monthly"]).default("daily") }), (data) => ({ period:{ start: new Date().toISOString(), end: new Date().toISOString() }, included:10000, consumed:7430, overage:0, overageCost:0, series: [] as Array<{ date:string; units:number; cost:number }> }));
  },

  /** Apply discount code. */
  applyPromoCode(ctx) {
    return ctx.mutate(z.object({ orgId: z.string(), code: z.string().min(4).max(32) }), (data) => ({ applied: true, discountPercent: 20 }));
  },

  /** Attach new payment method. */
  updatePaymentMethod(ctx) {
    return ctx.mutate(z.object({ orgId: z.string(), paymentMethodId: z.string() }), (data) => ({ updated: true }));
  },

  /** Update VAT/tax ID settings. */
  taxSettings(ctx) {
    return ctx.mutate(z.object({ orgId: z.string(), taxId: z.string().optional(), taxIdType: z.enum(["eu_vat","us_ein","au_abn","gb_vat"]).optional(), address: z.object({ country: z.string().length(2), postalCode: z.string() }).optional() }), (data) => ({ updated: true }));
  },
});
