/**
 * Root Router Index
 * AUTO-GENERATED by generate-complex-routes.ts
 */

import { authRoutes } from "./auth";
import { usersRoutes } from "./users";
import { organizationsRoutes } from "./organizations";
import { billingRoutes } from "./billing";
import { projectsRoutes } from "./projects";
import { tasksRoutes } from "./tasks";
import { commentsRoutes } from "./comments";
import { filesRoutes } from "./files";
import { notificationsRoutes } from "./notifications";
import { searchRoutes } from "./search";
import { analyticsRoutes } from "./analytics";
import { webhooksRoutes } from "./webhooks";
import { aiRoutes } from "./ai";
import { auditRoutes } from "./audit";
import { apiKeysRoutes } from "./api-keys";
import { integrationsRoutes } from "./integrations";
import { workflowsRoutes } from "./workflows";
import { documentsRoutes } from "./documents";
import { teamsRoutes } from "./teams";
import { invitesRoutes } from "./invites";
import { permissionsRoutes } from "./permissions";
import { reportsRoutes } from "./reports";
import { tagsRoutes } from "./tags";
import { rateLimitsRoutes } from "./rate-limits";
import { exportsRoutes } from "./exports";

export const appRouter = {
  authRoutes,
  usersRoutes,
  organizationsRoutes,
  billingRoutes,
  projectsRoutes,
  tasksRoutes,
  commentsRoutes,
  filesRoutes,
  notificationsRoutes,
  searchRoutes,
  analyticsRoutes,
  webhooksRoutes,
  aiRoutes,
  auditRoutes,
  apiKeysRoutes,
  integrationsRoutes,
  workflowsRoutes,
  documentsRoutes,
  teamsRoutes,
  invitesRoutes,
  permissionsRoutes,
  reportsRoutes,
  tagsRoutes,
  rateLimitsRoutes,
  exportsRoutes,
};

export type AppRouter = typeof appRouter;
