/**
 * Routes — "ai" domain.
 * AUTO-GENERATED by generate-complex-routes.ts
 */
import { z } from "zod";
import { defineRoutes } from "../../../src/base";
import { authMiddleware } from "../../../src/middleware";

// --- Schemas & shared types ---

const ContentPartSchema = z.discriminatedUnion("type", [
  z.object({ type: z.literal("text"),        text: z.string() }),
  z.object({ type: z.literal("image_url"),   url: z.string().url(), detail: z.enum(["auto","low","high"]).default("auto") }),
  z.object({ type: z.literal("tool_use"),    toolCallId: z.string(), name: z.string(), input: z.record(z.string(), z.unknown()) }),
  z.object({ type: z.literal("tool_result"), toolCallId: z.string(), content: z.string(), isError: z.boolean().default(false) }),
]);
type ContentPart = z.infer<typeof ContentPartSchema>;

const MessageSchema = z.object({
  role: z.enum(["system","user","assistant","tool"]),
  content: z.union([z.string(), z.array(ContentPartSchema)]),
  name: z.string().optional(),
});
type Message = z.infer<typeof MessageSchema>;

const ToolSchema = z.object({ name: z.string().regex(/^[a-zA-Z0-9_-]{1,64}$/), description: z.string().max(1024), parameters: z.record(z.string(), z.unknown()), strict: z.boolean().default(false) });

const ChatRequestSchema = z.object({
  messages: z.array(MessageSchema).min(1).max(200),
  model: z.enum(["gpt-4o","gpt-4o-mini","claude-sonnet-4-5","claude-haiku-4-5","gemini-1.5-pro"]),
  systemPrompt: z.string().max(8000).optional(),
  tools: z.array(ToolSchema).max(32).optional(),
  toolChoice: z.union([z.literal("auto"), z.literal("none"), z.literal("required"), z.object({ type: z.literal("function"), name: z.string() })]).default("auto"),
  temperature: z.number().min(0).max(2).default(1),
  maxTokens: z.number().int().min(1).max(128_000).optional(),
  responseFormat: z.discriminatedUnion("type", [
    z.object({ type: z.literal("text") }),
    z.object({ type: z.literal("json_object") }),
    z.object({ type: z.literal("json_schema"), schema: z.record(z.string(), z.unknown()), strict: z.boolean().default(true) }),
  ]).default({ type:"text" }),
  stop: z.array(z.string().max(20)).max(4).optional(),
});

type StreamEvent =
  | { type:"content_delta"; text:string }
  | { type:"tool_call"; toolCallId:string; name:string; argumentsDelta:string }
  | { type:"finish"; finishReason:"stop"|"tool_calls"|"length"|"content_filter"; usage:{ promptTokens:number; completionTokens:number } }
  | { type:"error"; code:string; message:string };

// --- Route definitions ---

export const aiRoutes = defineRoutes({ middleware: [authMiddleware] })({
  /** Multi-model streaming chat. */
  chat(ctx) {
    return ctx.stream(ChatRequestSchema, async function* (data) {
      yield { type:"content_delta", text:"hello " } satisfies StreamEvent;
      yield { type: "done" as const };
    });
  },

  /** Non-streaming completion. */
  complete(ctx) {
    return ctx.mutate(ChatRequestSchema.extend({ stream: z.literal(false).default(false) }), (data) => ({ id:"msg_01", role:"assistant" as const, content:"Hello!" as Message["content"], finishReason:"stop" as const, usage:{ promptTokens:100, completionTokens:50 } }));
  },

  /** Batch embedding generation. */
  embed(ctx) {
    return ctx.mutate(z.object({ inputs: z.array(z.union([z.string().min(1).max(8192), z.object({ text:z.string(), id:z.string() })])).min(1).max(100), model: z.enum(["text-embedding-3-small","text-embedding-3-large"]), dimensions: z.number().int().min(64).max(3072).optional(), outputFormat: z.enum(["float","base64","int8"]).default("float") }), (data) => ({ embeddings: [] as Array<{ index:number; embedding:number[]; inputTokens:number }>, model:data.model, totalTokens:0 }));
  },

  /** Content moderation. */
  moderateContent(ctx) {
    return ctx.mutate(z.object({ inputs: z.array(z.object({ id:z.string(), text:z.string().max(10000) })).min(1).max(50), categories: z.array(z.enum(["hate","harassment","self_harm","sexual","violence","dangerous"])).optional() }), (data) => ({ results: [] as Array<{ id:string; flagged:boolean; categories:Partial<Record<string,boolean>>; scores:Partial<Record<string,number>> }> }));
  },

  /** Structured summarization. */
  summarize(ctx) {
    return ctx.mutate(z.object({ text: z.string().min(50).max(50000), format: z.enum(["bullets","paragraph","tldr"]).default("paragraph"), maxLength: z.number().int().max(1000).default(200), language: z.string().optional() }), (data) => ({ summary:"This document covers...", wordCount:42 }));
  },

  /** Token usage for billing period. */
  usageStats(ctx) {
    return ctx.query(z.object({ orgId: z.string(), period: z.enum(["current","30d","90d"]).default("current") }), (data) => ({ promptTokens:500000, completionTokens:200000, totalCost:12.50, byModel:{} as Record<string,{ tokens:number; cost:number }> }));
  },
});
