/**
 * Routes — "reports" domain.
 * AUTO-GENERATED by generate-complex-routes.ts
 */
import { z } from "zod";
import { defineRouter } from "../../../src/base";
import { authMiddleware } from "../../../src/middleware";

// --- Schemas & shared types ---

const ReportType = z.enum(["task_summary","user_activity","project_velocity","billing_usage","audit_digest","custom"]);

const ScheduleSchema = z.object({
  cron: z.string(),
  timezone: z.string().default("UTC"),
  recipients: z.array(z.email()).min(1).max(50),
  format: z.enum(["pdf","csv","html"]).default("pdf"),
});

const ReportSchema = z.object({
  id: z.string(), orgId: z.string(),
  name: z.string().min(1).max(200), type: ReportType,
  config: z.record(z.string(), z.unknown()),
  schedule: ScheduleSchema.nullable(),
  lastRunAt: z.string().datetime().nullable(),
  lastRunStatus: z.enum(["success","failed","running"]).nullable(),
  createdBy: z.string().uuid(),
  createdAt: z.string().datetime(),
});
type Report = z.infer<typeof ReportSchema>;

// --- Route definitions ---

export const reportsRoutes = defineRouter({ middleware: [authMiddleware] })({
  /** Saved reports for org. */
  list(ctx) {
    return ctx.query(z.object({ orgId:z.string() }), (data) => ({ reports: [] as Report[] }));
  },

  /** Create report definition. */
  create(ctx) {
    return ctx.mutate(ReportSchema.omit({ id:true, lastRunAt:true, lastRunStatus:true, createdAt:true }), (data) => ({ id:"rep_new", name: data.name }));
  },

  /** Update report. */
  update(ctx) {
    return ctx.mutate(ReportSchema.omit({ id:true, lastRunAt:true, lastRunStatus:true, createdAt:true }).partial().extend({ id:z.string() }), (data) => ({ id: data.id, updated:true }));
  },

  /** Delete report. */
  delete(ctx) {
    return ctx.mutate(z.object({ id: z.string() }), (data) => ({ deleted: true }));
  },

  /** Trigger report run. */
  run(ctx) {
    return ctx.mutate(z.object({ id:z.string(), format:z.enum(["pdf","csv","html"]).optional() }), (data) => ({ jobId:"job_rep_01", queued:true }));
  },

  /** Get report download URL. */
  download(ctx) {
    return ctx.query(z.object({ id:z.string(), runId:z.string() }), (data) => ({ url:"https://cdn.example.com/reports/rep_01.pdf", expiresIn:3600 }));
  },

  /** Stream report generation. */
  stream(ctx) {
    return ctx.stream(z.object({ id:z.string() }), async function* (data) {
      yield { type:"progress" as const, percent:50, stage:"collecting_data" as const };
      yield { type: "done" as const };
    });
  },
});
