/**
 * Routes — "organizations" domain.
 * AUTO-GENERATED by generate-complex-routes.ts
 */
import { z } from "zod";
import { defineRouter } from "../../../src/base";
import { authMiddleware } from "../../../src/middleware";

// --- Schemas & shared types ---

const PlanTier = z.enum(["free","starter","pro","business","enterprise"]);
type PlanTier = z.infer<typeof PlanTier>;

const OrgSettingsSchema = z.object({
  allowedDomains: z.array(z.string()).max(20).default([]),
  ssoRequired: z.boolean().default(false),
  mfaRequired: z.boolean().default(false),
  ipAllowlist: z.array(z.ipv4()).max(100).default([]),
  defaultRole: z.enum(["member","viewer"]).default("member"),
  sessionTimeoutMinutes: z.number().int().min(15).max(10080).default(1440),
  dataRetentionDays: z.number().int().min(30).max(3650).nullable().default(null),
  features: z.record(z.string(), z.boolean()).default({}),
});
type OrgSettings = z.infer<typeof OrgSettingsSchema>;

const OrgSchema = z.object({
  id: z.string(), name: z.string().min(2).max(100),
  slug: z.string().regex(/^[a-z0-9-]+$/),
  plan: PlanTier, memberCount: z.number().int().nonnegative(),
  logoUrl: z.string().url().nullable(),
  settings: OrgSettingsSchema,
  createdAt: z.string().datetime(),
});
type Org = z.infer<typeof OrgSchema>;

// --- Route definitions ---

export const organizationsRoutes = defineRouter({ middleware: [authMiddleware] })({
  /** Orgs accessible to caller. */
  list(ctx) {
    return ctx.query(z.object({ page: z.number().int().min(1).default(1), limit: z.number().int().max(50).default(10) }), (data) => ({ orgs: [] as Org[], total: 0 }));
  },

  /** Fetch org by ID. */
  get(ctx) {
    return ctx.query(z.object({ id: z.string() }), (data) => ({ id: data.id, name:"Acme", slug:"acme", plan:"enterprise" as PlanTier, memberCount:42, logoUrl:null, settings: OrgSettingsSchema.parse({}), createdAt: new Date().toISOString() } satisfies Org));
  },

  /** Create new org. */
  create(ctx) {
    return ctx.mutate(OrgSchema.omit({ id:true, memberCount:true, createdAt:true }).extend({ ownerId: z.string().uuid() }), (data) => ({ id:"org_new", slug: data.slug }));
  },

  /** Update org metadata. */
  update(ctx) {
    return ctx.mutate(z.object({ id: z.string(), name: z.string().min(2).max(100).optional(), logoUrl: z.string().url().nullable().optional(), settings: OrgSettingsSchema.partial().optional() }), (data) => ({ id: data.id, updated: true }));
  },

  /** Permanently delete org. */
  delete(ctx) {
    return ctx.mutate(z.object({ id: z.string(), confirmSlug: z.string() }), (data) => ({ deleted: true }));
  },

  /** List org members. */
  members(ctx) {
    return ctx.query(z.object({ orgId: z.string(), page: z.number().int().min(1).default(1), limit: z.number().int().max(100).default(20) }), (data) => ({ members: [] as Array<{ userId:string; role:string; joinedAt:string }>, total: 0 }));
  },

  /** Add user to org. */
  addMember(ctx) {
    return ctx.mutate(z.object({ orgId: z.string(), userId: z.string().uuid(), role: z.enum(["owner","admin","member"]) }), (data) => ({ added: true }));
  },

  /** Remove user from org. */
  removeMember(ctx) {
    return ctx.mutate(z.object({ orgId: z.string(), userId: z.string().uuid() }), (data) => ({ removed: true }));
  },

  /** Transfer org ownership. */
  transferOwner(ctx) {
    return ctx.mutate(z.object({ orgId: z.string(), newOwnerId: z.string().uuid(), reason: z.string().optional() }), (data) => ({ transferred: true }));
  },

  /** Org-scoped audit log. */
  auditLog(ctx) {
    return ctx.query(z.object({ orgId: z.string(), limit: z.number().int().max(100).default(25), cursor: z.string().optional() }), (data) => ({ entries: [] as Array<{ id:string; actor:string; action:string; ts:string }>, nextCursor: null as string | null }));
  },
});
