/**
 * Routes — "files" domain.
 * AUTO-GENERATED by generate-complex-routes.ts
 */
import { z } from "zod";
import { defineRouter } from "../../../src/base";
import { authMiddleware } from "../../../src/middleware";

// --- Schemas & shared types ---

const FileStatus = z.enum(["pending","processing","ready","failed","deleted"]);

const FileMetaSchema = z.object({
  id: z.string(), name: z.string().min(1).max(255),
  mimeType: z.string(), sizeBytes: z.number().int().positive(),
  status: FileStatus, url: z.string().url().nullable(),
  thumbnailUrl: z.string().url().nullable(),
  resourceType: z.enum(["project","task","comment","message","profile"]),
  resourceId: z.string(),
  uploadedBy: z.string().uuid(),
  metadata: z.record(z.string(), z.union([z.string(), z.number()])),
  createdAt: z.string().datetime(),
});
type FileMeta = z.infer<typeof FileMetaSchema>;

// --- Route definitions ---

export const filesRoutes = defineRouter({ middleware: [authMiddleware] })({
  /** Files for a resource. */
  list(ctx) {
    return ctx.query(z.object({ resourceType: z.enum(["project","task","comment","message","profile"]), resourceId: z.string(), mimeTypes: z.array(z.string()).optional(), page: z.number().int().min(1).default(1) }), (data) => ({ files: [] as FileMeta[], total: 0 }));
  },

  /** File metadata by ID. */
  get(ctx) {
    return ctx.query(z.object({ id: z.string() }), (data) => ({ id:data.id, name:"design.png", mimeType:"image/png", sizeBytes:204800, status:"ready" as const, url:"https://cdn.example.com/f", thumbnailUrl:null, resourceType:"task" as const, resourceId:"task_01", uploadedBy:"usr_01", metadata:{}, createdAt: new Date().toISOString() } satisfies FileMeta));
  },

  /** Presigned S3 upload URL. */
  requestUpload(ctx) {
    return ctx.mutate(z.object({ fileName: z.string().min(1).max(255), mimeType: z.string(), sizeBytes: z.number().int().max(100_000_000), resourceType: z.enum(["project","task","comment","message","profile"]), resourceId: z.string() }), (data) => ({ uploadUrl:"https://s3.amazonaws.com/presigned", fileId:"file_pending", expiresIn:3600 }));
  },

  /** Mark upload complete. */
  confirmUpload(ctx) {
    return ctx.mutate(z.object({ fileId: z.string(), etag: z.string() }), (data) => ({ id:data.fileId, confirmed:true, url:"https://cdn.example.com/"+data.fileId }));
  },

  /** Delete file and storage object. */
  delete(ctx) {
    return ctx.mutate(z.object({ id: z.string() }), (data) => ({ deleted: true }));
  },

  /** Delete multiple files. */
  bulkDelete(ctx) {
    return ctx.mutate(z.object({ ids: z.array(z.string()).min(1).max(100) }), (data) => ({ deleted: data.ids.length }));
  },

  /** Trigger thumbnail generation. */
  generateThumb(ctx) {
    return ctx.mutate(z.object({ fileId: z.string(), width: z.number().int().min(16).max(2048).default(256), height: z.number().int().min(16).max(2048).default(256), fit: z.enum(["cover","contain","fill"]).default("cover") }), (data) => ({ jobId:"job_thumb", queued:true }));
  },

  /** Stream file processing events. */
  processStream(ctx) {
    return ctx.stream(z.object({ fileId: z.string() }), async function* (data) {
      yield { type:"progress" as const, fileId:data.fileId, percent:50, stage:"virus_scan" as const };
      yield { type: "done" as const };
    });
  },
});
