/**
 * Routes — "tasks" domain.
 * AUTO-GENERATED by generate-complex-routes.ts
 */
import { z } from "zod";
import { defineRoutes } from "../../../src/base";
import { authMiddleware } from "../../../src/middleware";

// --- Schemas & shared types ---

const TaskStatus = z.enum(["backlog","todo","in_progress","in_review","blocked","done","cancelled","wont_fix"]);
type TaskStatus = z.infer<typeof TaskStatus>;

const TaskPriority = z.enum(["critical","high","medium","low","none"]);

const CustomFieldValueSchema = z.discriminatedUnion("type", [
  z.object({ type: z.literal("text"),    value: z.string().max(1000) }),
  z.object({ type: z.literal("number"),  value: z.number() }),
  z.object({ type: z.literal("date"),    value: z.string().datetime() }),
  z.object({ type: z.literal("boolean"), value: z.boolean() }),
  z.object({ type: z.literal("select"),  value: z.string(), optionId: z.string() }),
  z.object({ type: z.literal("multi"),   value: z.array(z.string()), optionIds: z.array(z.string()) }),
  z.object({ type: z.literal("user"),    value: z.string().uuid() }),
  z.object({ type: z.literal("url"),     value: z.string().url() }),
]);
type CustomFieldValue = z.infer<typeof CustomFieldValueSchema>;

type TaskNode = {
  id: string; title: string;
  status: TaskStatus; priority: z.infer<typeof TaskPriority>;
  subtasks?: TaskNode[];
  customFields: Record<string, CustomFieldValue>;
};

const TaskCreateSchema = z.object({
  projectId: z.string(), title: z.string().min(1).max(500),
  description: z.string().max(50000).optional(),
  status: TaskStatus.default("backlog"), priority: TaskPriority.default("medium"),
  assigneeIds: z.array(z.string().uuid()).max(10).default([]),
  parentId: z.string().optional(),
  dueDate: z.string().datetime().nullable().optional(),
  startDate: z.string().datetime().nullable().optional(),
  labels: z.array(z.string().max(50)).max(20).default([]),
  estimateHours: z.number().nonnegative().max(10000).optional(),
  customFields: z.record(z.string(), CustomFieldValueSchema).default({}),
  dependencies: z.array(z.object({ taskId:z.string(), type:z.enum(["blocks","blocked_by","relates_to","duplicates"]) })).default([]),
}).refine(d => !d.startDate || !d.dueDate || d.startDate <= d.dueDate, { message:"startDate must be before dueDate", path:["startDate"] });

// --- Route definitions ---

export const tasksRoutes = defineRoutes({ middleware: [authMiddleware] })({
  /** Create task with full fields. */
  create(ctx) {
    return ctx.mutate(TaskCreateSchema, (data) => ({ id:"task_new", title:data.title, status:data.status, priority:data.priority } satisfies Pick<TaskNode,"id"|"title"|"status"|"priority">));
  },

  /** Task tree with subtasks. */
  get(ctx) {
    return ctx.query(z.object({ id: z.string(), depth: z.number().int().min(0).max(5).default(1) }), (data) => ({ id:data.id, title:"Fix login", status:"todo" as TaskStatus, priority:"high" as const, subtasks:[] as TaskNode[], customFields:{} as Record<string,CustomFieldValue> } satisfies TaskNode));
  },

  /** Patch task fields. */
  update(ctx) {
    return ctx.mutate(TaskCreateSchema.partial().extend({ id: z.string() }), (data) => ({ id: data.id, updated: true }));
  },

  /** Delete task. */
  delete(ctx) {
    return ctx.mutate(z.object({ id: z.string() }), (data) => ({ deleted: true }));
  },

  /** Batch status/priority update. */
  bulkUpdate(ctx) {
    return ctx.mutate(z.object({ ids: z.array(z.string()).min(1).max(500), patch: z.object({ status: TaskStatus.optional(), priority: TaskPriority.optional(), assigneeIds: z.array(z.string().uuid()).max(10).optional(), dueDate: z.string().datetime().nullable().optional() }).refine(o => Object.values(o).some(v => v !== undefined), { message:"At least one field required" }) }), (data) => ({ updated: data.ids.length }));
  },

  /** Task comment thread. */
  comments(ctx) {
    return ctx.query(z.object({ taskId: z.string(), limit: z.number().int().max(100).default(50) }), (data) => ({ comments: [] as Array<{ id:string; body:string; author:string; createdAt:string; reactions: Record<string,string[]> }> }));
  },

  /** Post comment on task. */
  addComment(ctx) {
    return ctx.mutate(z.object({ taskId: z.string(), body: z.string().min(1).max(5000), mentions: z.array(z.string().uuid()).default([]) }), (data) => ({ id:"cmt_new", body: data.body }));
  },

  /** Typed audit trail. */
  timelineEvents(ctx) {
    return ctx.query(z.object({ taskId: z.string(), limit: z.number().int().max(100).default(50) }), (data) => ({ events: [] as Array<{ type:"created"; actor:string; ts:string } | { type:"status_change"; actor:string; ts:string; from:TaskStatus; to:TaskStatus } | { type:"assigned"; actor:string; ts:string; userId:string }> }));
  },

  /** Live project task updates. */
  activityStream(ctx) {
    return ctx.stream(z.object({ projectId: z.string() }), async function* (data) {
      yield { type:"task_updated" as const, taskId:"task_01", field:"status", value:"done" };
      yield { type: "done" as const };
    });
  },

  /** Tasks assigned to current user. */
  myTasks(ctx) {
    return ctx.query(z.object({ status: z.array(TaskStatus).optional(), projectId: z.string().optional(), limit: z.number().int().max(100).default(25) }), (data) => ({ tasks: [] as TaskNode[], total: 0 }));
  },
});
