/**
 * Routes — "documents" domain.
 * AUTO-GENERATED by generate-complex-routes.ts
 */
import { z } from "zod";
import { defineRoutes } from "../../../src/base";
import { authMiddleware } from "../../../src/middleware";

// --- Schemas & shared types ---

const BlockType = z.enum(["paragraph","heading1","heading2","heading3","bullet_list","numbered_list","code","quote","divider","image","table","callout","toggle"]);

const InlineMarkSchema = z.object({ bold:z.boolean().optional(), italic:z.boolean().optional(), code:z.boolean().optional(), link:z.string().url().optional(), color:z.string().optional() });

const BlockSchema = z.object({
  id: z.string(), type: BlockType,
  content: z.array(z.object({ text:z.string(), marks:InlineMarkSchema.optional() })).optional(),
  children: z.array(z.string()).default([]),
  attrs: z.record(z.string(), z.union([z.string(), z.number(), z.boolean()])).optional(),
});
type Block = z.infer<typeof BlockSchema>;

const DocumentSchema = z.object({
  id: z.string(), projectId: z.string(), title: z.string().min(1).max(500),
  blocks: z.array(BlockSchema),
  visibility: z.enum(["private","project","public"]),
  authorId: z.string().uuid(),
  collaborators: z.array(z.string().uuid()),
  version: z.number().int().nonnegative(),
  publishedAt: z.string().datetime().nullable(),
  createdAt: z.string().datetime(), updatedAt: z.string().datetime(),
});
type Document = z.infer<typeof DocumentSchema>;

// --- Route definitions ---

export const documentsRoutes = defineRoutes({ middleware: [authMiddleware] })({
  /** Documents in a project. */
  list(ctx) {
    return ctx.query(z.object({ projectId:z.string(), page:z.number().int().min(1).default(1), limit:z.number().int().max(50).default(20), search:z.string().optional() }), (data) => ({ documents: [] as Array<Pick<Document,"id"|"title"|"authorId"|"createdAt"|"updatedAt">>, total:0 }));
  },

  /** Full document with blocks. */
  get(ctx) {
    return ctx.query(z.object({ id:z.string(), version:z.number().int().optional() }), (data) => ({ id:data.id, projectId:"proj_01", title:"Design doc", blocks:[] as Block[], visibility:"project" as const, authorId:"usr_01", collaborators:[], version:1, publishedAt:null, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() } satisfies Document));
  },

  /** Create document. */
  create(ctx) {
    return ctx.mutation(DocumentSchema.omit({ id:true, version:true, createdAt:true, updatedAt:true, publishedAt:true }), (data) => ({ id:"doc_new", title: data.title }));
  },

  /** Update title/blocks/visibility. */
  update(ctx) {
    return ctx.mutation(z.object({ id:z.string(), title:z.string().min(1).max(500).optional(), blocks:z.array(BlockSchema).optional(), visibility:z.enum(["private","project","public"]).optional() }), (data) => ({ id:data.id, version:2 }));
  },

  /** Delete document. */
  delete(ctx) {
    return ctx.mutation(z.object({ id: z.string() }), (data) => ({ deleted: true }));
  },

  /** Publish document publicly. */
  publish(ctx) {
    return ctx.mutation(z.object({ id: z.string() }), (data) => ({ publishedAt: new Date().toISOString(), url:"https://docs.example.com/doc_01" }));
  },

  /** Document version history. */
  history(ctx) {
    return ctx.query(z.object({ id:z.string(), limit:z.number().int().max(50).default(20) }), (data) => ({ versions: [] as Array<{ version:number; editor:string; changedAt:string; summary:string }> }));
  },

  /** Collaborative edit event stream. */
  editStream(ctx) {
    return ctx.stream(z.object({ docId:z.string() }), async function* (data) {
      yield { type:"block_updated" as const, blockId:"blk_01", patch:{} as Record<string,unknown>, editorId:"usr_01" };
      yield { type: "done" as const };
    });
  },
});
