/**
 * Routes — "audit" domain.
 * AUTO-GENERATED by generate-complex-routes.ts
 */
import { z } from "zod";
import { defineRoutes } from "../../../src/base";
import { authMiddleware } from "../../../src/middleware";

// --- Schemas & shared types ---

const AuditAction = z.enum([
  "user.login","user.logout","user.created","user.updated","user.deactivated",
  "org.created","org.updated","org.deleted","org.member_added","org.member_removed",
  "task.created","task.updated","task.deleted","task.status_changed",
  "billing.plan_changed","billing.payment_failed",
  "file.uploaded","file.deleted",
  "webhook.created","webhook.deleted",
  "api_key.created","api_key.revoked",
  "settings.updated","sso.enabled","sso.disabled",
]);
type AuditAction = z.infer<typeof AuditAction>;

const AuditEntrySchema = z.object({
  id: z.string(), orgId: z.string(),
  actorId: z.string().uuid().nullable(), actorEmail: z.email().nullable(),
  action: AuditAction,
  resourceType: z.string().nullable(), resourceId: z.string().nullable(),
  metadata: z.record(z.string(), z.unknown()),
  ip: z.ipv4().nullable(), userAgent: z.string().nullable(),
  ts: z.string().datetime(),
});
type AuditEntry = z.infer<typeof AuditEntrySchema>;

// --- Route definitions ---

export const auditRoutes = defineRoutes({ middleware: [authMiddleware] })({
  /** Paginated audit log. */
  log(ctx) {
    return ctx.query(z.object({ orgId:z.string(), actorId:z.string().uuid().optional(), actions:z.array(AuditAction).optional(), resourceType:z.string().optional(), resourceId:z.string().optional(), from:z.string().datetime().optional(), to:z.string().datetime().optional(), page:z.number().int().min(1).default(1), limit:z.number().int().max(100).default(25) }), (data) => ({ entries: [] as AuditEntry[], total:0, page: data.page }));
  },

  /** Single audit entry. */
  getEntry(ctx) {
    return ctx.query(z.object({ id: z.string() }), (data) => ({ id:data.id, orgId:"org_01", actorId:"usr_01", actorEmail:"a@b.com", action:"user.login" as AuditAction, resourceType:null, resourceId:null, metadata:{}, ip:"1.2.3.4", userAgent:"Mozilla/5.0", ts: new Date().toISOString() } satisfies AuditEntry));
  },

  /** Stream audit log as NDJSON. */
  export(ctx) {
    return ctx.stream(z.object({ orgId:z.string(), from:z.string().datetime(), to:z.string().datetime(), actions:z.array(AuditAction).optional() }), async function* (data) {
      yield { type:"entry" as const, data:{} as AuditEntry };
      yield { type: "done" as const };
    });
  },

  /** Update log retention policy. */
  retention(ctx) {
    return ctx.mutation(z.object({ orgId:z.string(), retentionDays:z.number().int().min(30).max(3650) }), (data) => ({ updated:true, retentionDays: data.retentionDays }));
  },
});
