/**
 * Routes — "rate-limits" domain.
 * AUTO-GENERATED by generate-complex-routes.ts
 */
import { z } from "zod";
import { defineRoutes } from "../../../src/base";
import { authMiddleware } from "../../../src/middleware";

// --- Schemas & shared types ---

const RateLimitTarget = z.enum(["api_key","user","org","ip","endpoint"]);

const RateLimitRuleSchema = z.object({
  id: z.string(), orgId: z.string(),
  name: z.string().min(1).max(200),
  target: RateLimitTarget,
  targetId: z.string().nullable(),
  endpoint: z.string().nullable(),
  limits: z.array(z.object({
    window: z.enum(["second","minute","hour","day"]),
    max: z.number().int().min(1),
    burstAllowance: z.number().int().nonnegative().default(0),
  })).min(1).max(4),
  action: z.enum(["throttle","block","log"]).default("throttle"),
  enabled: z.boolean().default(true),
  createdAt: z.string().datetime(),
});
type RateLimitRule = z.infer<typeof RateLimitRuleSchema>;

// --- Route definitions ---

export const rateLimitsRoutes = defineRoutes({ middleware: [authMiddleware] })({
  /** Rate limit rules for org. */
  listRules(ctx) {
    return ctx.query(z.object({ orgId:z.string(), target:RateLimitTarget.optional() }), (data) => ({ rules: [] as RateLimitRule[] }));
  },

  /** Create rate limit rule. */
  createRule(ctx) {
    return ctx.mutate(RateLimitRuleSchema.omit({ id:true, createdAt:true }), (data) => ({ id:"rl_new", name: data.name }));
  },

  /** Update rule. */
  updateRule(ctx) {
    return ctx.mutate(RateLimitRuleSchema.omit({ id:true, createdAt:true }).partial().extend({ id:z.string() }), (data) => ({ id: data.id, updated:true }));
  },

  /** Delete rule. */
  deleteRule(ctx) {
    return ctx.mutate(z.object({ id: z.string() }), (data) => ({ deleted: true }));
  },

  /** Current usage against limits. */
  currentStatus(ctx) {
    return ctx.query(z.object({ orgId:z.string(), target:RateLimitTarget.optional() }), (data) => ({ statuses: [] as Array<{ ruleId:string; target:z.infer<typeof RateLimitTarget>; window:string; current:number; max:number; resetAt:string }> }));
  },

  /** Manually reset a counter. */
  resetCounter(ctx) {
    return ctx.mutate(z.object({ ruleId:z.string(), targetId:z.string() }), (data) => ({ reset: true }));
  },
});
