/**
 * Routes — "search" domain.
 * AUTO-GENERATED by generate-complex-routes.ts
 */
import { z } from "zod";
import { defineRoutes } from "../../../src/base";
import { authMiddleware } from "../../../src/middleware";

// --- Schemas & shared types ---

const SearchableType = z.enum(["task","project","user","file","comment","workflow","document"]);

const SearchResultSchema = z.discriminatedUnion("type", [
  z.object({ type: z.literal("task"),     id:z.string(), title:z.string(), status:z.string(), projectId:z.string(), score:z.number() }),
  z.object({ type: z.literal("project"),  id:z.string(), name:z.string(), status:z.string(), score:z.number() }),
  z.object({ type: z.literal("user"),     id:z.string(), name:z.string(), email:z.string(), score:z.number() }),
  z.object({ type: z.literal("file"),     id:z.string(), name:z.string(), mimeType:z.string(), score:z.number() }),
  z.object({ type: z.literal("comment"),  id:z.string(), body:z.string(), resourceId:z.string(), score:z.number() }),
  z.object({ type: z.literal("workflow"), id:z.string(), name:z.string(), score:z.number() }),
  z.object({ type: z.literal("document"), id:z.string(), title:z.string(), score:z.number() }),
]);
type SearchResult = z.infer<typeof SearchResultSchema>;

// --- Route definitions ---

export const searchRoutes = defineRoutes({ middleware: [authMiddleware] })({
  /** Full-text search across resources. */
  global(ctx) {
    return ctx.query(z.object({ q: z.string().min(1).max(200), types: z.array(SearchableType).default(["task","project","user"]), orgId: z.string(), limit: z.number().int().max(50).default(10), highlight: z.boolean().default(true) }), (data) => ({ results: [] as SearchResult[], total:0, took:42 }));
  },

  /** Autocomplete suggestions. */
  suggestions(ctx) {
    return ctx.query(z.object({ q: z.string().min(1).max(100), orgId: z.string(), types: z.array(SearchableType).optional() }), (data) => ({ suggestions: [] as Array<{ label:string; type:z.infer<typeof SearchableType>; id:string }> }));
  },

  /** Faceted filter counts. */
  filters(ctx) {
    return ctx.query(z.object({ q: z.string().min(1), orgId: z.string(), types: z.array(SearchableType).optional() }), (data) => ({ facets: {} as Record<z.infer<typeof SearchableType>, number> }));
  },

  /** Search index health and stats. */
  indexStatus(ctx) {
    return ctx.query(z.object({ orgId: z.string() }), (data) => ({ indexed:10000, lag:0, lastUpdated: new Date().toISOString() }));
  },

  /** Stream results for large corpora. */
  stream(ctx) {
    return ctx.stream(z.object({ q: z.string().min(1), orgId: z.string(), types: z.array(SearchableType).optional() }), async function* (data) {
      yield { type:"result" as const, result: {} as SearchResult };
      yield { type: "done" as const };
    });
  },

  /** Trigger manual reindex. */
  reindex(ctx) {
    return ctx.mutation(z.object({ orgId: z.string(), types: z.array(SearchableType).optional() }), (data) => ({ jobId:"job_reindex", queued:true }));
  },
});
