/**
 * Routes — "integrations" domain.
 * AUTO-GENERATED by generate-complex-routes.ts
 */
import { z } from "zod";
import { defineRouter } from "../../../src/base";
import { authMiddleware } from "../../../src/middleware";

// --- Schemas & shared types ---

const IntegrationId = z.enum(["slack","github","jira","linear","notion","figma","google_drive","dropbox","salesforce","hubspot","zendesk","pagerduty"]);
type IntegrationId = z.infer<typeof IntegrationId>;

const IntegrationStatusSchema = z.object({
  id: IntegrationId, name: z.string(),
  installed: z.boolean(), enabled: z.boolean(),
  status: z.enum(["active","error","disconnected","syncing"]),
  lastSyncAt: z.string().datetime().nullable(),
  errorMessage: z.string().nullable(),
  config: z.record(z.string(), z.unknown()),
});
type IntegrationStatus = z.infer<typeof IntegrationStatusSchema>;

// --- Route definitions ---

export const integrationsRoutes = defineRouter({ middleware: [authMiddleware] })({
  /** All integrations with status. */
  list(ctx) {
    return ctx.query(z.object({ orgId: z.string() }), (data) => ({ integrations: [] as IntegrationStatus[] }));
  },

  /** Single integration status. */
  get(ctx) {
    return ctx.query(z.object({ orgId: z.string(), integrationId: IntegrationId }), (data) => ({ id:data.integrationId, name:"Slack", installed:true, enabled:true, status:"active" as const, lastSyncAt: new Date().toISOString(), errorMessage:null, config:{} } satisfies IntegrationStatus));
  },

  /** Start OAuth install flow. */
  install(ctx) {
    return ctx.mutate(z.object({ orgId: z.string(), integrationId: IntegrationId, redirectUri: z.string().url(), scopes: z.array(z.string()).optional() }), (data) => ({ authUrl:"https://slack.com/oauth/authorize?..." }));
  },

  /** Exchange OAuth code for tokens. */
  oauthCallback(ctx) {
    return ctx.mutate(z.object({ code: z.string(), state: z.string(), integrationId: IntegrationId }), (data) => ({ installed:true, integrationId: data.integrationId }));
  },

  /** Remove integration and revoke. */
  uninstall(ctx) {
    return ctx.mutate(z.object({ orgId: z.string(), integrationId: IntegrationId }), (data) => ({ uninstalled: true }));
  },

  /** Update integration configuration. */
  updateConfig(ctx) {
    return ctx.mutate(z.object({ orgId: z.string(), integrationId: IntegrationId, config: z.record(z.string(), z.unknown()) }), (data) => ({ updated: true }));
  },

  /** Manual sync trigger. */
  triggerSync(ctx) {
    return ctx.mutate(z.object({ orgId: z.string(), integrationId: IntegrationId }), (data) => ({ jobId:"job_sync_01", queued:true }));
  },

  /** Stream sync progress events. */
  syncStream(ctx) {
    return ctx.stream(z.object({ orgId: z.string(), integrationId: IntegrationId }), async function* (data) {
      yield { type:"progress" as const, integrationId:data.integrationId, itemsSynced:10, total:100 };
      yield { type: "done" as const };
    });
  },
});
