/**
 * Routes — "workflows" domain.
 * AUTO-GENERATED by generate-complex-routes.ts
 */
import { z } from "zod";
import { defineRoutes } from "../../../src/base";
import { authMiddleware } from "../../../src/middleware";

// --- Schemas & shared types ---

const ActionSchema = z.discriminatedUnion("type", [
  z.object({ type: z.literal("send_email"),    to:z.array(z.email()), subject:z.string(), templateId:z.string() }),
  z.object({ type: z.literal("send_slack"),    channelId:z.string(), message:z.string().max(3000) }),
  z.object({ type: z.literal("webhook"),       url:z.string().url(), method:z.enum(["GET","POST","PUT","PATCH"]), headers:z.record(z.string(), z.string()).optional(), body:z.record(z.string(), z.unknown()).optional() }),
  z.object({ type: z.literal("update_field"),  resourceType:z.string(), resourceId:z.string(), field:z.string(), value:z.unknown() }),
  z.object({ type: z.literal("create_task"),   projectId:z.string(), title:z.string(), assigneeId:z.string().uuid().optional() }),
  z.object({ type: z.literal("ai_summarize"),  inputField:z.string(), outputField:z.string(), model:z.string().optional() }),
]);
type WorkflowAction = z.infer<typeof ActionSchema>;

const ConditionSchema: z.ZodType<ConditionNode> = z.lazy(() => z.discriminatedUnion("kind", [
  z.object({ kind: z.literal("leaf"),    field:z.string(), operator:z.enum(["eq","neq","gt","gte","lt","lte","contains","isNull"]), value:z.union([z.string(), z.number(), z.boolean(), z.null()]) }),
  z.object({ kind: z.literal("and"),     conditions:z.array(z.lazy(() => ConditionSchema)).min(2) }),
  z.object({ kind: z.literal("or"),      conditions:z.array(z.lazy(() => ConditionSchema)).min(2) }),
  z.object({ kind: z.literal("not"),     condition:z.lazy(() => ConditionSchema) }),
]));
type ConditionNode = { kind:"leaf"; field:string; operator:string; value:unknown } | { kind:"and"; conditions:ConditionNode[] } | { kind:"or"; conditions:ConditionNode[] } | { kind:"not"; condition:ConditionNode };

const WorkflowDefSchema = z.object({
  name: z.string().min(1).max(200), description: z.string().max(1000).optional(),
  trigger: z.object({ event:z.string(), filters:ConditionSchema.optional(), debounceMs:z.number().int().nonnegative().optional() }),
  steps: z.array(z.object({ id:z.string(), name:z.string(), type:z.enum(["condition","action","delay","parallel"]), condition:ConditionSchema.optional(), action:ActionSchema.optional(), delayMs:z.number().int().nonnegative().optional(), nextStepIds:z.array(z.string()).default([]) })).min(1).max(50),
  enabled: z.boolean().default(true),
  retryPolicy: z.object({ maxAttempts:z.number().int().min(1).max(10), backoffMs:z.number().int().min(100), backoffMultiplier:z.number().min(1).max(10) }).optional(),
});

// --- Route definitions ---

export const workflowsRoutes = defineRoutes({ middleware: [authMiddleware] })({
  /** Create workflow with recursive conditions. */
  create(ctx) {
    return ctx.mutation(WorkflowDefSchema.extend({ orgId: z.string() }), (data) => ({ id:"wf_new", name:data.name, enabled:data.enabled }));
  },

  /** List workflows with run stats. */
  list(ctx) {
    return ctx.query(z.object({ orgId:z.string(), enabled:z.boolean().optional() }), (data) => ({ workflows: [] as Array<{ id:string; name:string; enabled:boolean; lastRunAt:string|null; runCount:number; failureRate:number }> }));
  },

  /** Workflow detail with definition. */
  get(ctx) {
    return ctx.query(z.object({ id: z.string() }), (data) => ({ id:data.id, name:"On task created", enabled:true, trigger:{ event:"task.created" }, steps:[], retryPolicy:undefined }));
  },

  /** Update workflow definition. */
  update(ctx) {
    return ctx.mutation(WorkflowDefSchema.partial().extend({ id: z.string() }), (data) => ({ id: data.id, updated: true }));
  },

  /** Delete workflow. */
  delete(ctx) {
    return ctx.mutation(z.object({ id: z.string() }), (data) => ({ deleted: true }));
  },

  /** Paginated run history. */
  runHistory(ctx) {
    return ctx.query(z.object({ workflowId:z.string(), status:z.enum(["running","success","failed","cancelled"]).optional(), limit:z.number().int().max(100).default(25), cursor:z.string().optional() }), (data) => ({ runs: [] as Array<{ id:string; status:string; startedAt:string; finishedAt:string|null; steps:Array<{ stepId:string; status:string; durationMs:number; error?:string }> }>, nextCursor:null as string|null }));
  },

  /** Dry-run with streamed step outcomes. */
  testRun(ctx) {
    return ctx.stream(z.object({ workflowId:z.string(), samplePayload:z.record(z.string(), z.unknown()) }), async function* (data) {
      yield { type:"step_result" as const, stepId:"step_01", status:"success" as const, durationMs:12, output:{} as Record<string,unknown> };
      yield { type: "done" as const };
    });
  },
});
