/**
 * Routes — "api-keys" domain.
 * AUTO-GENERATED by generate-complex-routes.ts
 */
import { z } from "zod";
import { defineRoutes } from "../../../src/base";
import { authMiddleware } from "../../../src/middleware";

// --- Schemas & shared types ---

const ApiKeyScope = z.enum([
  "read:all","write:all",
  "tasks:read","tasks:write",
  "users:read","users:write",
  "billing:read","analytics:read",
  "webhooks:manage","files:read","files:write",
]);
type ApiKeyScope = z.infer<typeof ApiKeyScope>;

const ApiKeySchema = z.object({
  id: z.string(), orgId: z.string(), name: z.string().min(1).max(100),
  prefix: z.string().length(8),
  scopes: z.array(ApiKeyScope).min(1),
  expiresAt: z.string().datetime().nullable(),
  lastUsedAt: z.string().datetime().nullable(),
  createdBy: z.string().uuid(),
  createdAt: z.string().datetime(),
  rateLimit: z.object({ requestsPerMinute: z.number().int().min(1).max(10000), requestsPerDay: z.number().int().min(1).max(1000000) }).nullable(),
});
type ApiKey = z.infer<typeof ApiKeySchema>;

// --- Route definitions ---

export const apiKeysRoutes = defineRoutes({ middleware: [authMiddleware] })({
  /** List API keys for org. */
  list(ctx) {
    return ctx.query(z.object({ orgId: z.string() }), (data) => ({ keys: [] as ApiKey[] }));
  },

  /** Create API key. */
  create(ctx) {
    return ctx.mutate(ApiKeySchema.omit({ id:true, prefix:true, lastUsedAt:true, createdAt:true }).extend({ orgId:z.string() }), (data) => ({ key:"sk_live_xxxxxxxx", id:"key_new", prefix:"sk_live_" }));
  },

  /** Revoke an API key. */
  revoke(ctx) {
    return ctx.mutate(z.object({ id: z.string(), reason: z.string().max(500).optional() }), (data) => ({ revoked: true }));
  },

  /** Rotate key secret. */
  rotate(ctx) {
    return ctx.mutate(z.object({ id: z.string() }), (data) => ({ newKey:"sk_live_yyyyyyyy", id: data.id }));
  },

  /** API key metadata. */
  get(ctx) {
    return ctx.query(z.object({ id: z.string() }), (data) => ({ id:data.id, orgId:"org_01", name:"CI Key", prefix:"sk_live_", scopes:["read:all" as ApiKeyScope], expiresAt:null, lastUsedAt:null, createdBy:"usr_01", createdAt: new Date().toISOString(), rateLimit:null } satisfies ApiKey));
  },

  /** Key request usage stats. */
  usage(ctx) {
    return ctx.query(z.object({ id: z.string(), period: z.enum(["1h","24h","7d","30d"]).default("24h") }), (data) => ({ requests:1234, errors:2, p50Ms:45, p99Ms:320, series: [] as Array<{ ts:string; count:number }> }));
  },
});
