/**
 * Routes — "teams" domain.
 * AUTO-GENERATED by generate-complex-routes.ts
 */
import { z } from "zod";
import { defineRoutes } from "../../../src/base";
import { authMiddleware } from "../../../src/middleware";

// --- Schemas & shared types ---

const TeamSchema = z.object({
  id: z.string(), orgId: z.string(),
  name: z.string().min(1).max(100),
  description: z.string().max(1000).optional(),
  color: z.string().regex(/^#[0-9a-fA-F]{6}$/).optional(),
  icon: z.string().max(4).optional(),
  visibility: z.enum(["public","private","secret"]),
  memberCount: z.number().int().nonnegative(),
  projectIds: z.array(z.string()),
  createdAt: z.string().datetime(),
});
type Team = z.infer<typeof TeamSchema>;

// --- Route definitions ---

export const teamsRoutes = defineRoutes({ middleware: [authMiddleware] })({
  /** Teams in an org. */
  list(ctx) {
    return ctx.query(z.object({ orgId:z.string(), visibility:z.enum(["public","private","secret"]).optional() }), (data) => ({ teams: [] as Team[] }));
  },

  /** Team by ID. */
  get(ctx) {
    return ctx.query(z.object({ id: z.string() }), (data) => ({ id:data.id, orgId:"org_01", name:"Engineering", description:undefined, color:"#3B82F6", icon:"⚙️", visibility:"public" as const, memberCount:12, projectIds:[], createdAt: new Date().toISOString() } satisfies Team));
  },

  /** Create team. */
  create(ctx) {
    return ctx.mutate(TeamSchema.omit({ id:true, memberCount:true, createdAt:true }), (data) => ({ id:"team_new", name: data.name }));
  },

  /** Update team metadata. */
  update(ctx) {
    return ctx.mutate(TeamSchema.omit({ id:true, memberCount:true, createdAt:true }).partial().extend({ id:z.string() }), (data) => ({ id: data.id, updated:true }));
  },

  /** Delete team. */
  delete(ctx) {
    return ctx.mutate(z.object({ id: z.string() }), (data) => ({ deleted: true }));
  },

  /** Team member list. */
  members(ctx) {
    return ctx.query(z.object({ teamId:z.string(), page:z.number().int().min(1).default(1) }), (data) => ({ members: [] as Array<{ userId:string; role:z.infer<typeof z.enum(["lead","member"])>; joinedAt:string }> }));
  },

  /** Add user to team. */
  addMember(ctx) {
    return ctx.mutate(z.object({ teamId:z.string(), userId:z.string().uuid(), role:z.enum(["lead","member"]) }), (data) => ({ added: true }));
  },

  /** Remove user from team. */
  removeMember(ctx) {
    return ctx.mutate(z.object({ teamId:z.string(), userId:z.string().uuid() }), (data) => ({ removed: true }));
  },
});
