/**
 * Routes — "analytics" domain.
 * AUTO-GENERATED by generate-complex-routes.ts
 */
import { z } from "zod";
import { defineRoutes } from "../../../src/base";
import { authMiddleware } from "../../../src/middleware";

// --- Schemas & shared types ---

const Granularity = z.enum(["minute","hour","day","week","month"]);

const FilterOperatorSchema = z.discriminatedUnion("op", [
  z.object({ op: z.literal("eq"),      value: z.union([z.string(), z.number(), z.boolean()]) }),
  z.object({ op: z.literal("neq"),     value: z.union([z.string(), z.number(), z.boolean()]) }),
  z.object({ op: z.literal("gt"),      value: z.number() }),
  z.object({ op: z.literal("gte"),     value: z.number() }),
  z.object({ op: z.literal("lt"),      value: z.number() }),
  z.object({ op: z.literal("lte"),     value: z.number() }),
  z.object({ op: z.literal("in"),      values: z.array(z.union([z.string(), z.number()])).min(1).max(100) }),
  z.object({ op: z.literal("between"), min: z.number(), max: z.number() }),
]);
type FilterOperator = z.infer<typeof FilterOperatorSchema>;

const QuerySchema = z.object({
  orgId: z.string(),
  metrics: z.array(z.string()).min(1).max(20),
  dimensions: z.array(z.string()).max(10).default([]),
  filters: z.array(z.object({ field:z.string(), operator:FilterOperatorSchema })).max(30).default([]),
  dateRange: z.object({ from:z.string().datetime(), to:z.string().datetime(), granularity:Granularity.default("day"), timezone:z.string().default("UTC") }),
  orderBy: z.array(z.object({ field:z.string(), direction:z.enum(["asc","desc"]) })).max(5).default([]),
  limit: z.number().int().max(10_000).default(1000),
  compareWith: z.object({ from:z.string().datetime(), to:z.string().datetime() }).optional(),
});
type AnalyticsQuery = z.infer<typeof QuerySchema>;

type QueryResult = {
  rows: Array<Record<string, string | number | boolean | null>>;
  totals: Record<string, number>;
  comparison?: Record<string, { current:number; previous:number; changePercent:number }>;
  meta: { executionMs:number; rowsScanned:number; cached:boolean; granularity:z.infer<typeof Granularity> };
};

// --- Route definitions ---

export const analyticsRoutes = defineRoutes({ middleware: [authMiddleware] })({
  /** Arbitrary analytics query. */
  query(ctx) {
    return ctx.mutation(QuerySchema, (data) => ({ rows:[], totals:{}, comparison:undefined, meta:{ executionMs:42, rowsScanned:10000, cached:false, granularity:data.dateRange.granularity } } satisfies QueryResult));
  },

  /** Multi-step funnel conversion. */
  funnel(ctx) {
    return ctx.mutation(z.object({ orgId:z.string(), steps:z.array(z.object({ name:z.string(), event:z.string(), filters:z.array(z.object({ field:z.string(), operator:FilterOperatorSchema })).default([]) })).min(2).max(10), dateRange:z.object({ from:z.string().datetime(), to:z.string().datetime() }) }), (data) => ({ steps: [] as Array<{ name:string; count:number; conversionRate:number; avgTimeToNextStep:number|null }>, overallConversion:0 }));
  },

  /** Cohort retention analysis. */
  retention(ctx) {
    return ctx.mutation(z.object({ orgId:z.string(), cohortEvent:z.string(), returnEvent:z.string(), dateRange:z.object({ from:z.string().datetime(), to:z.string().datetime() }), granularity:Granularity.default("week") }), (data) => ({ cohorts: [] as Array<{ date:string; size:number; retention:number[] }> }));
  },

  /** Saved report definitions. */
  savedReports(ctx) {
    return ctx.query(z.object({ orgId: z.string() }), (data) => ({ reports: [] as Array<{ id:string; name:string; query:AnalyticsQuery; schedule:{ cron:string; recipients:string[] }|null; lastRunAt:string|null }> }));
  },

  /** Persist a report definition. */
  saveReport(ctx) {
    return ctx.mutation(z.object({ orgId:z.string(), name:z.string().min(1).max(200), query:QuerySchema, schedule:z.object({ cron:z.string(), recipients:z.array(z.email()).min(1) }).optional() }), (data) => ({ id:"report_new", name: data.name }));
  },

  /** Stream query results row by row. */
  exportStream(ctx) {
    return ctx.stream(QuerySchema.extend({ format:z.enum(["json","csv","parquet"]).default("json") }), async function* (data) {
      yield { type:"row" as const, index:0, data:{} as Record<string, string|number|null> };
      yield { type: "done" as const };
    });
  },
});
