/**
 * Routes — "webhooks" domain.
 * AUTO-GENERATED by generate-complex-routes.ts
 */
import { z } from "zod";
import { defineRoutes } from "../../../src/base";
import { authMiddleware } from "../../../src/middleware";

// --- Schemas & shared types ---

const WebhookEventType = z.enum([
  "task.created",
  "task.updated",
  "task.deleted",
  "task.status_changed",
  "user.created",
  "user.updated",
  "user.deactivated",
  "project.created",
  "project.archived",
  "billing.subscription_updated",
  "billing.invoice_paid",
  "billing.payment_failed",
  "file.uploaded",
  "file.deleted",
  "workflow.run_completed",
  "workflow.run_failed",
]);
type WebhookEventType = z.infer<typeof WebhookEventType>;

const WebhookSchema = z.object({
  id: z.string(),
  orgId: z.string(),
  url: z.string().url(),
  description: z.string().max(500).optional(),
  events: z.array(WebhookEventType).min(1),
  enabled: z.boolean(),
  secret: z.string().min(16),
  headers: z.record(z.string(), z.string()).default({}),
  retryPolicy: z
    .object({
      maxAttempts: z.number().int().min(1).max(10),
      backoffMs: z.number().int().min(100),
    })
    .default({ maxAttempts: 3, backoffMs: 1000 }),
  createdAt: z.string().datetime(),
});
type Webhook = z.infer<typeof WebhookSchema>;

// --- Route definitions ---

export const webhooksRoutes = defineRoutes({ middleware: [authMiddleware] })({
  /** Webhooks for an org. */
  list(ctx) {
    return ctx.query(z.object({ orgId: z.string() }), (data) => ({
      webhooks: [] as Webhook[],
    }));
  },

  /** Webhook by ID. */
  get(ctx) {
    return ctx.query(
      z.object({ id: z.string() }),
      (data) =>
        ({
          id: data.id,
          orgId: "org_01",
          url: "https://example.com/hook",
          events: ["task.created" as WebhookEventType],
          enabled: true,
          secret: "***",
          headers: {},
          retryPolicy: { maxAttempts: 3, backoffMs: 1000 },
          createdAt: new Date().toISOString(),
        } satisfies Omit<Webhook, "description">)
    );
  },

  /** Register webhook. */
  create(ctx) {
    return ctx.mutate(
      WebhookSchema.omit({ id: true, createdAt: true }),
      (data) => ({ id: "wh_new", url: data.url })
    );
  },

  /** Update webhook. */
  update(ctx) {
    return ctx.mutate(
      WebhookSchema.omit({ id: true, createdAt: true })
        .partial()
        .extend({ id: z.string() }),
      (data) => ({ id: data.id, updated: true })
    );
  },

  /** Remove webhook. */
  delete(ctx) {
    return ctx.mutate(z.object({ id: z.string() }), (data) => ({
      deleted: true,
    }));
  },

  /** Recent delivery attempts. */
  deliveries(ctx) {
    return ctx.query(
      z.object({
        webhookId: z.string(),
        status: z.enum(["success", "failed", "pending"]).optional(),
        limit: z.number().int().max(50).default(20),
      }),
      (data) => ({
        deliveries: [] as Array<{
          id: string;
          status: number;
          attempt: number;
          ts: string;
          error: string | null;
        }>,
      })
    );
  },

  /** Retry failed delivery. */
  redeliver(ctx) {
    return ctx.mutate(z.object({ deliveryId: z.string() }), (data) => ({
      queued: true,
    }));
  },

  /** Send test event to webhook. */
  testPing(ctx) {
    return ctx.mutate(
      z.object({ webhookId: z.string(), eventType: WebhookEventType }),
      (data) => ({ sent: true, deliveryId: "del_test" })
    );
  },
});
