/**
 * Routes — "users" domain.
 * AUTO-GENERATED by generate-complex-routes.ts
 */
import { z } from "zod";
import { defineRoutes } from "../../../src/base";
import { authMiddleware } from "../../../src/middleware";

// --- Schemas & shared types ---

const RoleSchema = z.enum(["owner","admin","member","viewer","billing","developer","support"]);
type Role = z.infer<typeof RoleSchema>;

const AddressSchema = z.object({ line1: z.string().max(200), line2: z.string().max(200).optional(), city: z.string().max(100), state: z.string().max(100).optional(), postalCode: z.string().max(20), country: z.string().length(2) });

const UserProfileSchema = z.object({
  id: z.string().uuid(), email: z.email(), emailVerified: z.boolean(),
  name: z.string().min(1).max(120), displayName: z.string().max(60).optional(),
  avatarUrl: z.string().url().nullable(), bio: z.string().max(500).optional(),
  timezone: z.string().optional(), locale: z.string().regex(/^[a-z]{2}(-[A-Z]{2})?$/).optional(),
  role: RoleSchema, permissions: z.array(z.string()),
  metadata: z.record(z.string(), z.union([z.string(), z.number(), z.boolean()])),
  address: AddressSchema.optional(),
  createdAt: z.string().datetime(), updatedAt: z.string().datetime(),
});
type UserProfile = z.infer<typeof UserProfileSchema>;

const UserUpdateSchema = UserProfileSchema
  .pick({ name:true, displayName:true, bio:true, timezone:true, locale:true, avatarUrl:true })
  .extend({ address: AddressSchema.optional() })
  .partial();

// --- Route definitions ---

export const usersRoutes = defineRoutes({ middleware: [authMiddleware] })({
  /** Paginated user list. */
  list(ctx) {
    return ctx.query(z.object({ page: z.number().int().min(1).default(1), limit: z.number().int().max(100).default(20), roles: z.array(RoleSchema).optional(), search: z.string().max(200).optional(), emailVerified: z.boolean().optional(), sortBy: z.enum(["name","email","createdAt","lastSeen"]).default("createdAt"), sortDir: z.enum(["asc","desc"]).default("desc") }), (data) => ({ users: [] as UserProfile[], total: 0, page: data.page, pageCount: 0 }));
  },

  /** Fetch single user. */
  get(ctx) {
    return ctx.query(z.object({ id: z.string().uuid() }), (data) => ({ id: data.id, email:"a@b.com", emailVerified:true, name:"Alice", displayName:undefined, avatarUrl:null, bio:undefined, timezone:"UTC", locale:"en-US", role:"member" as Role, permissions:[], metadata:{}, address:undefined, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() } satisfies UserProfile));
  },

  /** Create user account. */
  create(ctx) {
    return ctx.mutate(UserProfileSchema.omit({ id:true, createdAt:true, updatedAt:true, emailVerified:true, permissions:true }).extend({ password: z.string().min(8) }), (data) => ({ id:"usr_new", email: data.email }));
  },

  /** Partial profile update. */
  update(ctx) {
    return ctx.mutate(UserUpdateSchema.extend({ id: z.string().uuid() }), (data) => ({ id: data.id, updated: true }));
  },

  /** Soft-delete user. */
  deactivate(ctx) {
    return ctx.mutate(z.object({ id: z.string().uuid(), reason: z.string().max(500).optional() }), (data) => ({ deactivated: true }));
  },

  /** Change role for many users. */
  bulkRoleChange(ctx) {
    return ctx.mutate(z.object({ userIds: z.array(z.string().uuid()).min(1).max(500), role: RoleSchema, reason: z.string().max(500).optional() }), (data) => ({ updated: data.userIds.length, role: data.role }));
  },

  /** All permissions by resource. */
  permissionMatrix(ctx) {
    return ctx.query(z.object({ userId: z.string().uuid() }), (data) => ({ userId: data.userId, matrix: {} as Record<string, Record<string, boolean>> }));
  },

  /** Recent activity events. */
  activityLog(ctx) {
    return ctx.query(z.object({ userId: z.string().uuid(), limit: z.number().int().max(100).default(20) }), (data) => ({ events: [] as Array<{ action: string; ts: string; meta: Record<string, unknown> }> }));
  },

  /** Admin impersonation token. */
  impersonate(ctx) {
    return ctx.mutate(z.object({ targetUserId: z.string().uuid(), reason: z.string().min(10) }), (data) => ({ impersonationToken: "imp.jwt", expiresIn: 900 }));
  },

  /** GDPR data export stream. */
  exportData(ctx) {
    return ctx.stream(z.object({ userId: z.string().uuid() }), async function* (data) {
      yield { type:"chunk" as const, resource:"profile" as const, data: {} as Record<string, unknown> };
      yield { type: "done" as const };
    });
  },
});
