/**
 * Routes — "permissions" domain.
 * AUTO-GENERATED by generate-complex-routes.ts
 */
import { z } from "zod";
import { defineRouter } from "../../../src/base";
import { authMiddleware } from "../../../src/middleware";

// --- Schemas & shared types ---

const Resource = z.enum(["task","project","document","file","comment","team","org","billing","webhook","api_key","integration","workflow","analytics"]);
type Resource = z.infer<typeof Resource>;

const Action = z.enum(["create","read","update","delete","manage","share","export","import","approve"]);
type Action = z.infer<typeof Action>;

const PolicyEffect = z.enum(["allow","deny"]);

const PolicyConditionSchema = z.object({
  field: z.string(),
  operator: z.enum(["eq","neq","in","owned_by"]),
  value: z.union([z.string(), z.array(z.string()), z.literal("$userId"), z.literal("$orgId")]),
});

const PolicySchema = z.object({
  id: z.string(), orgId: z.string(), name: z.string().min(1).max(200),
  effect: PolicyEffect,
  resources: z.array(Resource).min(1),
  actions: z.array(Action).min(1),
  conditions: z.array(PolicyConditionSchema).default([]),
  subjects: z.array(z.object({ type:z.enum(["user","team","role"]), id:z.string() })).min(1),
  priority: z.number().int().min(0).max(1000).default(0),
  createdAt: z.string().datetime(),
});
type Policy = z.infer<typeof PolicySchema>;

// --- Route definitions ---

export const permissionsRoutes = defineRouter({ middleware: [authMiddleware] })({
  /** All policies for org. */
  listPolicies(ctx) {
    return ctx.query(z.object({ orgId:z.string() }), (data) => ({ policies: [] as Policy[] }));
  },

  /** Create ABAC policy. */
  createPolicy(ctx) {
    return ctx.mutate(PolicySchema.omit({ id:true, createdAt:true }), (data) => ({ id:"pol_new", name: data.name }));
  },

  /** Update policy definition. */
  updatePolicy(ctx) {
    return ctx.mutate(PolicySchema.omit({ id:true, createdAt:true }).partial().extend({ id:z.string() }), (data) => ({ id: data.id, updated:true }));
  },

  /** Delete policy. */
  deletePolicy(ctx) {
    return ctx.mutate(z.object({ id: z.string() }), (data) => ({ deleted: true }));
  },

  /** Evaluate access for subject. */
  checkAccess(ctx) {
    return ctx.query(z.object({ orgId:z.string(), subjectId:z.string().uuid(), resource:Resource, action:Action, resourceId:z.string().optional() }), (data) => ({ allowed:true, matchedPolicies: [] as string[] }));
  },

  /** Batch permission check. */
  bulkCheck(ctx) {
    return ctx.mutate(z.object({ orgId:z.string(), subjectId:z.string().uuid(), checks:z.array(z.object({ resource:Resource, action:Action, resourceId:z.string().optional() })).min(1).max(100) }), (data) => ({ results: [] as Array<{ resource:Resource; action:Action; allowed:boolean }> }));
  },
});
