/**
 * Routes — "comments" domain.
 * AUTO-GENERATED by generate-complex-routes.ts
 */
import { z } from "zod";
import { defineRouter } from "../../../src/base";
import { authMiddleware } from "../../../src/middleware";

// --- Schemas & shared types ---

const ResourceType = z.enum(["task","project","document","file","post"]);

const ReactionSchema = z.object({ emoji: z.string().max(8), users: z.array(z.string().uuid()) });

const CommentSchema = z.object({
  id: z.string(), resourceType: ResourceType, resourceId: z.string(),
  authorId: z.string().uuid(), body: z.string().min(1).max(50000),
  bodyHtml: z.string().optional(),
  mentions: z.array(z.string().uuid()),
  reactions: z.array(ReactionSchema),
  attachments: z.array(z.object({ id:z.string(), name:z.string(), url:z.string().url() })),
  parentId: z.string().nullable(),
  editedAt: z.string().datetime().nullable(),
  createdAt: z.string().datetime(),
});
type Comment = z.infer<typeof CommentSchema>;

// --- Route definitions ---

export const commentsRoutes = defineRouter({ middleware: [authMiddleware] })({
  /** Comments for a resource. */
  list(ctx) {
    return ctx.query(z.object({ resourceType: ResourceType, resourceId: z.string(), cursor: z.string().optional(), limit: z.number().int().max(100).default(25) }), (data) => ({ comments: [] as Comment[], nextCursor: null as string | null }));
  },

  /** Post a comment. */
  create(ctx) {
    return ctx.mutate(CommentSchema.omit({ id:true, bodyHtml:true, reactions:true, editedAt:true, createdAt:true }), (data) => ({ id:"cmt_new" }));
  },

  /** Edit comment body. */
  update(ctx) {
    return ctx.mutate(z.object({ id: z.string(), body: z.string().min(1).max(50000) }), (data) => ({ id: data.id, updated: true }));
  },

  /** Delete comment. */
  delete(ctx) {
    return ctx.mutate(z.object({ id: z.string() }), (data) => ({ deleted: true }));
  },

  /** Toggle emoji reaction. */
  react(ctx) {
    return ctx.mutate(z.object({ commentId: z.string(), emoji: z.string().max(8) }), (data) => ({ added: true, emoji: data.emoji }));
  },

  /** Threaded replies for comment. */
  thread(ctx) {
    return ctx.query(z.object({ parentId: z.string(), limit: z.number().int().max(50).default(20) }), (data) => ({ replies: [] as Comment[], total: 0 }));
  },

  /** Mark comment thread resolved. */
  resolve(ctx) {
    return ctx.mutate(z.object({ commentId: z.string() }), (data) => ({ resolved: true }));
  },

  /** Stream new comments live. */
  liveStream(ctx) {
    return ctx.stream(z.object({ resourceType: ResourceType, resourceId: z.string() }), async function* (data) {
      yield { type:"new_comment" as const, comment: {} as Comment };
      yield { type: "done" as const };
    });
  },
});
