/**
 * Routes — "invites" domain.
 * AUTO-GENERATED by generate-complex-routes.ts
 */
import { z } from "zod";
import { defineRoutes } from "../../../src/base";
import { authMiddleware } from "../../../src/middleware";

// --- Schemas & shared types ---

const InviteStatus = z.enum(["pending","accepted","declined","expired","revoked"]);

const InviteSchema = z.object({
  id: z.string(), orgId: z.string(),
  email: z.email(),
  role: z.enum(["owner","admin","member","viewer"]),
  status: InviteStatus,
  invitedBy: z.string().uuid(),
  expiresAt: z.string().datetime(),
  acceptedAt: z.string().datetime().nullable(),
  teams: z.array(z.string()).default([]),
  personalMessage: z.string().max(500).optional(),
  createdAt: z.string().datetime(),
});
type Invite = z.infer<typeof InviteSchema>;

// --- Route definitions ---

export const invitesRoutes = defineRoutes({ middleware: [authMiddleware] })({
  /** Pending invites for org. */
  list(ctx) {
    return ctx.query(z.object({ orgId:z.string(), status:InviteStatus.optional() }), (data) => ({ invites: [] as Invite[] }));
  },

  /** Send invite. */
  create(ctx) {
    return ctx.mutation(InviteSchema.omit({ id:true, status:true, invitedBy:true, expiresAt:true, acceptedAt:true, createdAt:true }), (data) => ({ id:"inv_new", email:data.email }));
  },

  /** Bulk invite by email list. */
  bulkCreate(ctx) {
    return ctx.mutation(z.object({ orgId:z.string(), emails:z.array(z.email()).min(1).max(50), role:z.enum(["admin","member","viewer"]).default("member"), teams:z.array(z.string()).default([]) }), (data) => ({ invited:data.emails.length, failed:[] as string[] }));
  },

  /** Accept an invite. */
  accept(ctx) {
    return ctx.mutation(z.object({ token:z.string() }), (data) => ({ accepted:true, orgId:"org_01" }));
  },

  /** Decline an invite. */
  decline(ctx) {
    return ctx.mutation(z.object({ token:z.string() }), (data) => ({ declined: true }));
  },

  /** Revoke a pending invite. */
  revoke(ctx) {
    return ctx.mutation(z.object({ id:z.string() }), (data) => ({ revoked: true }));
  },

  /** Resend invite email. */
  resend(ctx) {
    return ctx.mutation(z.object({ id:z.string() }), (data) => ({ sent: true }));
  },
});
