// ─── Generated by tsdkarc-x openapi codegen ─────────────────────────────────
// Source: ./src/x/demos/x.json
// Mode:   both
// Do not edit manually — regenerate with generateFromOpenApi()

import { defineRoutes } from "../adapters/app.hono";
import { z } from "zod";

// ─── Proxy fetch helpers ──────────────────────────────────────────────────────

async function proxyGet(url: string): Promise<unknown> {
  const res = await fetch(url, { method: "GET" });
  if (!res.ok)
    throw Object.assign(
      new Error(`[proxy] GET ${url} → HTTP ${res.status}`),
      { status: res.status }
    );
  return res.json();
}

async function proxyPost(url: string, data: unknown): Promise<unknown> {
  const res = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(data ?? {}),
  });
  if (!res.ok)
    throw Object.assign(
      new Error(`[proxy] POST ${url} → HTTP ${res.status}`),
      { status: res.status }
    );
  return res.json();
}

export const xModule = defineRoutes()({
  user: {
    /**
     * Get user by ID.
     */
    get(ctx) {
      return ctx.query(
        z.object({
      id: z.string(),
      msg: z.number().optional()
    }),
        (_data) => {
          return {
      "id": "id_value",
      "name": "John Doe"
    }
        }
      );
    },

    /**
     * Create a new user.
     */
    create(ctx) {
      return ctx.mutate(
        z.object({
      name: z.string()
    }),
        (_data) => {
          return {
      "name": "John Doe",
      "id": "id_value"
    }
        }
      );
    }
  },

  /**
   * Health check.
   */
  ping(ctx) {
    return {
    "pong": true
  };
  }
});
export const xModuleProxy = defineRoutes()({
  user: {
    /**
     * Get user by ID.
     */
    get(ctx) {
      return ctx.query(
        z.object({
      id: z.string(),
      msg: z.number().optional()
    }),
        (data) => proxyGet((() => {
      const params = new URLSearchParams();
        params.set("id", String(data.id));
        params.set("msg", String(data.msg));
      return `http://localhost:5001/user/get?${params}`;
    })())
      );
    },

    /**
     * Create a new user.
     */
    create(ctx) {
      return ctx.mutate(
        z.object({
      name: z.string()
    }),
        (data) => proxyPost(`http://localhost:5001/user/create`, data)
      );
    }
  },

  /**
   * Health check.
   */
  ping(ctx) {
    return ctx.query(() => proxyGet(`http://localhost:5001/ping`));
  }
});