/**
 * Routes — "tags" domain.
 * AUTO-GENERATED by generate-complex-routes.ts
 */
import { z } from "zod";
import { defineRouter } from "../../../src/base";
import { authMiddleware } from "../../../src/middleware";

// --- Schemas & shared types ---

const TagSchema = z.object({
  id: z.string(), orgId: z.string(),
  name: z.string().min(1).max(80),
  color: z.string().regex(/^#[0-9a-fA-F]{6}$/),
  description: z.string().max(300).optional(),
  usageCount: z.number().int().nonnegative(),
  createdAt: z.string().datetime(),
});
type Tag = z.infer<typeof TagSchema>;

// --- Route definitions ---

export const tagsRoutes = defineRouter({ middleware: [authMiddleware] })({
  /** All tags for org. */
  list(ctx) {
    return ctx.query(z.object({ orgId:z.string(), search:z.string().optional(), sortBy:z.enum(["name","usageCount"]).default("usageCount") }), (data) => ({ tags: [] as Tag[] }));
  },

  /** Create tag. */
  create(ctx) {
    return ctx.mutate(TagSchema.omit({ id:true, usageCount:true, createdAt:true }), (data) => ({ id:"tag_new", name: data.name }));
  },

  /** Update tag name/color. */
  update(ctx) {
    return ctx.mutate(z.object({ id:z.string(), name:z.string().min(1).max(80).optional(), color:z.string().regex(/^#[0-9a-fA-F]{6}$/).optional(), description:z.string().max(300).optional() }), (data) => ({ id: data.id, updated:true }));
  },

  /** Delete tag. */
  delete(ctx) {
    return ctx.mutate(z.object({ id: z.string() }), (data) => ({ deleted: true }));
  },

  /** Merge tags into one. */
  merge(ctx) {
    return ctx.mutate(z.object({ sourceIds:z.array(z.string()).min(2).max(20), targetId:z.string() }), (data) => ({ merged: data.sourceIds.length, targetId: data.targetId }));
  },

  /** Attach tags to resources. */
  attach(ctx) {
    return ctx.mutate(z.object({ tagIds:z.array(z.string()).min(1).max(20), resourceType:z.enum(["task","project","document"]), resourceId:z.string() }), (data) => ({ attached: data.tagIds.length }));
  },

  /** Detach tags from resource. */
  detach(ctx) {
    return ctx.mutate(z.object({ tagIds:z.array(z.string()).min(1), resourceType:z.enum(["task","project","document"]), resourceId:z.string() }), (data) => ({ detached: data.tagIds.length }));
  },
});
