/**
 * Routes — "notifications" domain.
 * AUTO-GENERATED by generate-complex-routes.ts
 */
import { z } from "zod";
import { defineRouter } from "../../../src/base";
import { authMiddleware } from "../../../src/middleware";

// --- Schemas & shared types ---

const NotifType = z.enum(["mention","task_assigned","task_completed","comment","billing","security","system","workflow_run","integration_sync"]);

const NotifPayloadSchema = z.discriminatedUnion("type", [
  z.object({ type: z.literal("mention"),          commentId: z.string(), resourceType: z.string(), resourceId: z.string() }),
  z.object({ type: z.literal("task_assigned"),    taskId: z.string(), projectId: z.string() }),
  z.object({ type: z.literal("task_completed"),   taskId: z.string(), completedBy: z.string().uuid() }),
  z.object({ type: z.literal("comment"),          commentId: z.string(), taskId: z.string() }),
  z.object({ type: z.literal("billing"),          invoiceId: z.string(), amount: z.number(), currency: z.string() }),
  z.object({ type: z.literal("security"),         event: z.string(), ip: z.ipv4().optional() }),
  z.object({ type: z.literal("system"),           message: z.string() }),
  z.object({ type: z.literal("workflow_run"),     workflowId: z.string(), status: z.enum(["success","failed"]) }),
  z.object({ type: z.literal("integration_sync"), integrationId: z.string(), itemsSynced: z.number().int() }),
]);
type NotifPayload = z.infer<typeof NotifPayloadSchema>;

const NotifSchema = z.object({
  id: z.string(), type: NotifType, read: z.boolean(),
  payload: NotifPayloadSchema, createdAt: z.string().datetime(),
  actorId: z.string().uuid().nullable(),
});
type Notif = z.infer<typeof NotifSchema>;

// --- Route definitions ---

export const notificationsRoutes = defineRouter({ middleware: [authMiddleware] })({
  /** Paginated notification list. */
  list(ctx) {
    return ctx.query(z.object({ unreadOnly: z.boolean().default(false), types: z.array(NotifType).optional(), limit: z.number().int().max(50).default(20), cursor: z.string().optional() }), (data) => ({ notifications: [] as Notif[], unreadCount:3, nextCursor: null as string | null }));
  },

  /** Mark notifications read. */
  markRead(ctx) {
    return ctx.mutate(z.object({ ids: z.array(z.string()).min(1).max(100) }), (data) => ({ marked: data.ids.length }));
  },

  /** Mark all as read. */
  markAllRead(ctx) {
    return ctx.mutate(z.object({}), (data) => ({ marked: true }));
  },

  /** Notification preferences. */
  preferences(ctx) {
    return ctx.query(z.object({}), (data) => ({ channels: { email:true, push:false, inApp:true } as Record<string,boolean>, types: {} as Partial<Record<z.infer<typeof NotifType>, boolean>> }));
  },

  /** Update preferences. */
  updatePreferences(ctx) {
    return ctx.mutate(z.object({ channels: z.record(z.string(), z.boolean()).optional(), types: z.record(z.string(), z.boolean()).optional() }), (data) => ({ updated: true }));
  },

  /** Real-time notification SSE. */
  stream(ctx) {
    return ctx.stream(z.object({}), async function* (data) {
      yield { type:"notification" as const, notification: {} as Notif };
      yield { type: "done" as const };
    });
  },

  /** Register push subscription. */
  pushSubscribe(ctx) {
    return ctx.mutate(z.object({ endpoint: z.string().url(), keys: z.object({ p256dh: z.string(), auth: z.string() }) }), (data) => ({ subscribed: true }));
  },
});
