/**
 * Routes — "projects" domain.
 * AUTO-GENERATED by generate-complex-routes.ts
 */
import { z } from "zod";
import { defineRoutes } from "../../../src/base";
import { authMiddleware } from "../../../src/middleware";

// --- Schemas & shared types ---

const ProjectStatus = z.enum(["planning","active","on_hold","completed","archived","cancelled"]);

const ProjectSchema = z.object({
  id: z.string(), orgId: z.string(),
  name: z.string().min(1).max(120),
  description: z.string().max(5000).optional(),
  status: ProjectStatus,
  visibility: z.enum(["private","internal","public"]),
  startDate: z.string().datetime().nullable(),
  endDate: z.string().datetime().nullable(),
  ownerId: z.string().uuid(),
  tags: z.array(z.string().max(50)).max(20),
  customFields: z.record(z.string(), z.union([z.string(), z.number(), z.boolean(), z.null()])),
  createdAt: z.string().datetime(), updatedAt: z.string().datetime(),
}).refine(p => !p.startDate || !p.endDate || p.startDate <= p.endDate, { message: "startDate must be before endDate" });
type Project = z.infer<typeof ProjectSchema>;

// --- Route definitions ---

export const projectsRoutes = defineRoutes({ middleware: [authMiddleware] })({
  /** Paginated project list. */
  list(ctx) {
    return ctx.query(z.object({ orgId: z.string(), status: z.array(ProjectStatus).optional(), search: z.string().optional(), page: z.number().int().min(1).default(1), limit: z.number().int().max(50).default(10) }), (data) => ({ projects: [] as Project[], total:0 }));
  },

  /** Project by ID. */
  get(ctx) {
    return ctx.query(z.object({ id: z.string() }), (data) => ({ id:data.id, orgId:"org_01", name:"Alpha", status:"active" as const, visibility:"private" as const, startDate:null, endDate:null, ownerId:"usr_01", tags:[], customFields:{}, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() } satisfies Project));
  },

  /** Create project. */
  create(ctx) {
    return ctx.mutate(ProjectSchema.omit({ id:true, createdAt:true, updatedAt:true }), (data) => ({ id:"proj_new", name: data.name }));
  },

  /** Update project. */
  update(ctx) {
    return ctx.mutate(ProjectSchema.omit({ id:true, createdAt:true, updatedAt:true }).partial().extend({ id: z.string() }), (data) => ({ id: data.id, updated:true }));
  },

  /** Archive project. */
  archive(ctx) {
    return ctx.mutate(z.object({ id: z.string(), reason: z.string().max(500).optional() }), (data) => ({ archived: true }));
  },

  /** Project members. */
  members(ctx) {
    return ctx.query(z.object({ projectId: z.string() }), (data) => ({ members: [] as Array<{ userId:string; role:z.infer<typeof z.enum(["lead","contributor","viewer"])>; joinedAt:string }> }));
  },

  /** Add project member. */
  addMember(ctx) {
    return ctx.mutate(z.object({ projectId: z.string(), userId: z.string().uuid(), role: z.enum(["lead","contributor","viewer"]) }), (data) => ({ added: true }));
  },

  /** Project aggregate stats. */
  stats(ctx) {
    return ctx.query(z.object({ projectId: z.string(), period: z.enum(["7d","30d","90d"]).default("30d") }), (data) => ({ tasks:42, completed:30, openIssues:5, velocity:8.2, burndownPoints: [] as Array<{ date:string; remaining:number }> }));
  },

  /** Clone project structure. */
  duplicate(ctx) {
    return ctx.mutate(z.object({ id: z.string(), newName: z.string().min(1).max(120), includeTasks: z.boolean().default(true), includeMembers: z.boolean().default(false) }), (data) => ({ id:"proj_clone", name: data.newName }));
  },

  /** Stream full project export. */
  export(ctx) {
    return ctx.stream(z.object({ id: z.string(), format: z.enum(["json","csv"]) }), async function* (data) {
      yield { type:"row" as const, resource:"task" as const, data:{} as Record<string,unknown> };
      yield { type: "done" as const };
    });
  },
});
