/**
 * Routes — "auth" domain.
 * AUTO-GENERATED by generate-complex-routes.ts
 */
import { z } from "zod";
import { defineRoutes } from "../../../src/base";


// --- Schemas & shared types ---

type Brand<T, B extends string> = T & { readonly __brand: B };
type UserId   = Brand<string, "UserId">;
type SessionId = Brand<string, "SessionId">;

const CredentialSchema = z.discriminatedUnion("method", [
  z.object({ method: z.literal("password"),   email: z.email(), password: z.string().min(8).max(128), totpCode: z.string().length(6).optional() }),
  z.object({ method: z.literal("oauth"),      provider: z.enum(["google","github","microsoft","okta"]), code: z.string(), redirectUri: z.string().url(), state: z.string() }),
  z.object({ method: z.literal("saml"),       orgSlug: z.string().regex(/^[a-z0-9-]+$/), samlResponse: z.string(), relayState: z.string().optional() }),
  z.object({ method: z.literal("magic_link"),  token: z.string().min(32) }),
  z.object({ method: z.literal("passkey"),     credentialId: z.string(), response: z.object({ authenticatorData: z.string(), clientDataJSON: z.string(), signature: z.string() }) }),
]);

const DeviceSchema = z.object({
  userAgent: z.string().max(512),
  ip: z.ipv4(),
  fingerprint: z.string().optional(),
  platform: z.enum(["web","ios","android","desktop"]).optional(),
});

const TokenPairSchema = z.object({
  accessToken: z.string(),
  refreshToken: z.string(),
  expiresIn: z.number().int().positive(),
  tokenType: z.literal("Bearer"),
  scope: z.array(z.string()),
});
type TokenPair = z.infer<typeof TokenPairSchema>;

const LoginSchema = z.intersection(CredentialSchema, z.object({ device: DeviceSchema.optional() }));

// --- Route definitions ---

export const authRoutes = defineRoutes({})({
  /** Multi-method login. */
  login(ctx) {
    return ctx.mutation(LoginSchema, (data) => ({ tokens: { accessToken:"jwt.a", refreshToken:"jwt.r", expiresIn:3600, tokenType:"Bearer" as const, scope:["read"] } satisfies TokenPair, user: { id:"usr_01" as UserId } }));
  },

  /** Rotate tokens. */
  refresh(ctx) {
    return ctx.mutation(z.object({ refreshToken: z.string(), sessionId: z.string().uuid() }), (data) => ({ accessToken:"jwt.new", refreshToken:"jwt.r2", expiresIn:3600, tokenType:"Bearer" as const, scope:["read"] } satisfies TokenPair));
  },

  /** Invalidate session. */
  logout(ctx) {
    return ctx.mutation(z.object({ sessionId: z.string().uuid() }), (data) => ({ revoked: true, sessionId: data.sessionId as SessionId }));
  },

  /** Validate MFA after credential. */
  mfaChallenge(ctx) {
    return ctx.mutation(z.object({ challengeToken: z.string(), code: z.string().length(6), method: z.enum(["totp","sms","email","webauthn"]) }), (data) => ({ verified: true }));
  },

  /** Send reset link. */
  forgotPassword(ctx) {
    return ctx.mutation(z.object({ email: z.email() }), (data) => ({ sent: true }));
  },

  /** Apply new password. */
  resetPassword(ctx) {
    return ctx.mutation(z.object({ token: z.string(), newPassword: z.string().min(8) }), (data) => ({ success: true }));
  },

  /** List active sessions. */
  sessions(ctx) {
    return ctx.query(z.object({ cursor: z.string().optional(), limit: z.number().int().max(50).default(20) }), (data) => ({ sessions: [] as Array<{ id: SessionId; device: z.infer<typeof DeviceSchema>; createdAt: string; current: boolean }>, nextCursor: null as string | null }));
  },

  /** Current user profile. */
  me(ctx) {
    return ctx.query(z.object({}), (data) => ({ id: "usr_01" as UserId, email: "a@b.com", role: "admin" as const }));
  },

  /** Confirm email via code. */
  verifyEmail(ctx) {
    return ctx.mutation(z.object({ code: z.string().length(6) }), (data) => ({ verified: true }));
  },

  /** Handle OAuth code exchange. */
  oauthCallback(ctx) {
    return ctx.mutation(z.object({ code: z.string(), state: z.string(), provider: z.enum(["google","github","microsoft","okta"]) }), (data) => ({ tokens: { accessToken:"jwt.oauth", refreshToken:"jwt.r", expiresIn:3600, tokenType:"Bearer" as const, scope:["read"] } satisfies TokenPair }));
  },
});
