/**
 * Routes — "exports" domain.
 * AUTO-GENERATED by generate-complex-routes.ts
 */
import { z } from "zod";
import { defineRouter } from "../../../src/base";
import { authMiddleware } from "../../../src/middleware";

// --- Schemas & shared types ---

const ExportFormat = z.enum(["json","csv","xlsx","pdf","ndjson","parquet"]);
type ExportFormat = z.infer<typeof ExportFormat>;

const ExportResourceSchema = z.discriminatedUnion("resource", [
  z.object({ resource:z.literal("tasks"),     projectId:z.string().optional(), filters:z.record(z.string(), z.unknown()).optional() }),
  z.object({ resource:z.literal("users"),     orgId:z.string() }),
  z.object({ resource:z.literal("analytics"), orgId:z.string(), metrics:z.array(z.string()).min(1), dateRange:z.object({ from:z.string().datetime(), to:z.string().datetime() }) }),
  z.object({ resource:z.literal("audit_log"), orgId:z.string(), from:z.string().datetime(), to:z.string().datetime() }),
  z.object({ resource:z.literal("billing"),   orgId:z.string(), year:z.number().int().min(2020).max(2099) }),
  z.object({ resource:z.literal("files"),     resourceType:z.string(), resourceId:z.string() }),
]);
type ExportResource = z.infer<typeof ExportResourceSchema>;

const ExportJobSchema = z.object({
  id: z.string(), orgId: z.string(),
  resource: ExportResourceSchema,
  format: ExportFormat,
  status: z.enum(["queued","running","done","failed"]),
  progress: z.number().min(0).max(100),
  rowCount: z.number().int().nonnegative().nullable(),
  downloadUrl: z.string().url().nullable(),
  expiresAt: z.string().datetime().nullable(),
  error: z.string().nullable(),
  createdAt: z.string().datetime(),
});
type ExportJob = z.infer<typeof ExportJobSchema>;

// --- Route definitions ---

export const exportsRoutes = defineRouter({ middleware: [authMiddleware] })({
  /** Queue an export job. */
  create(ctx) {
    return ctx.mutate(z.object({ orgId:z.string(), resource:ExportResourceSchema, format:ExportFormat, notifyEmail:z.email().optional() }), (data) => ({ id:"exp_new", status:"queued" as const }));
  },

  /** Export job history. */
  list(ctx) {
    return ctx.query(z.object({ orgId:z.string(), limit:z.number().int().max(50).default(20) }), (data) => ({ jobs: [] as ExportJob[] }));
  },

  /** Export job status. */
  get(ctx) {
    return ctx.query(z.object({ id: z.string() }), (data) => ({ id:data.id, orgId:"org_01", resource:{ resource:"tasks" } satisfies ExportResource, format:"csv" as ExportFormat, status:"done" as const, progress:100, rowCount:500, downloadUrl:"https://cdn.example.com/exp.csv", expiresAt: new Date().toISOString(), error:null, createdAt: new Date().toISOString() } satisfies ExportJob));
  },

  /** Cancel queued export. */
  cancel(ctx) {
    return ctx.mutate(z.object({ id: z.string() }), (data) => ({ cancelled: true }));
  },

  /** Fresh signed download URL. */
  download(ctx) {
    return ctx.query(z.object({ id: z.string() }), (data) => ({ url:"https://cdn.example.com/exp.csv", expiresIn:3600 }));
  },

  /** Stream export progress. */
  progressStream(ctx) {
    return ctx.stream(z.object({ jobId: z.string() }), async function* (data) {
      yield { type:"progress" as const, jobId:data.jobId, percent:50, rowsProcessed:250 };
      yield { type: "done" as const };
    });
  },
});
